//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskoMask.BuildingBlocks.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractsMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractsMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskoMask.BuildingBlocks.Contracts.Resources.ContractsMetadata", typeof(ContractsMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog Tasks Count.
        /// </summary>
        public static string BacklogTasksCount {
            get {
                return ResourceManager.GetString("BacklogTasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardId.
        /// </summary>
        public static string BoardId {
            get {
                return ResourceManager.GetString("BoardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader.
        /// </summary>
        public static string BoardMemberAccessLevel_Reader {
            get {
                return ResourceManager.GetString("BoardMemberAccessLevel_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer.
        /// </summary>
        public static string BoardMemberAccessLevel_Writer {
            get {
                return ResourceManager.GetString("BoardMemberAccessLevel_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        public static string BoardName {
            get {
                return ResourceManager.GetString("BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards Count.
        /// </summary>
        public static string BoardsCount {
            get {
                return ResourceManager.GetString("BoardsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardId.
        /// </summary>
        public static string CardId {
            get {
                return ResourceManager.GetString("CardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards Count.
        /// </summary>
        public static string CardsCount {
            get {
                return ResourceManager.GetString("CardsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Type.
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlog.
        /// </summary>
        public static string CardType_Backlog {
            get {
                return ResourceManager.GetString("CardType_Backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing.
        /// </summary>
        public static string CardType_Doing {
            get {
                return ResourceManager.GetString("CardType_Doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string CardType_Done {
            get {
                return ResourceManager.GetString("CardType_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do.
        /// </summary>
        public static string CardType_ToDo {
            get {
                return ResourceManager.GetString("CardType_ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string ComparePasswords {
            get {
                return ResourceManager.GetString("ComparePasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date Time.
        /// </summary>
        public static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Day.
        /// </summary>
        public static string CreateDay {
            get {
                return ResourceManager.GetString("CreateDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Month.
        /// </summary>
        public static string CreateMonth {
            get {
                return ResourceManager.GetString("CreateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Year.
        /// </summary>
        public static string CreateYear {
            get {
                return ResourceManager.GetString("CreateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing Tasks Count.
        /// </summary>
        public static string DoingTasksCount {
            get {
                return ResourceManager.GetString("DoingTasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Tasks Count.
        /// </summary>
        public static string DoneTasksCount {
            get {
                return ResourceManager.GetString("DoneTasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} length must be between {1} and {2} characters.
        /// </summary>
        public static string Length_Error {
            get {
                return ResourceManager.GetString("Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} length can not be more than {1} characters.
        /// </summary>
        public static string Max_Length_Error {
            get {
                return ResourceManager.GetString("Max_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} length must be greater than {1} characters.
        /// </summary>
        public static string Min_Length_Error {
            get {
                return ResourceManager.GetString("Min_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date Time.
        /// </summary>
        public static string ModifiedDateTime {
            get {
                return ResourceManager.GetString("ModifiedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators Count.
        /// </summary>
        public static string OperatorsCount {
            get {
                return ResourceManager.GetString("OperatorsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationId.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations Count.
        /// </summary>
        public static string OrganizationsCount {
            get {
                return ResourceManager.GetString("OrganizationsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string OwnerDisplayName {
            get {
                return ResourceManager.GetString("OwnerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owners Count.
        /// </summary>
        public static string OwnersCount {
            get {
                return ResourceManager.GetString("OwnersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        public static string Permission_GroupName {
            get {
                return ResourceManager.GetString("Permission_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemName.
        /// </summary>
        public static string Permission_SystemName {
            get {
                return ResourceManager.GetString("Permission_SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Count.
        /// </summary>
        public static string PermissionsCount {
            get {
                return ResourceManager.GetString("PermissionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Count.
        /// </summary>
        public static string PermissionsId {
            get {
                return ResourceManager.GetString("PermissionsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectId.
        /// </summary>
        public static string ProjectId {
            get {
                return ResourceManager.GetString("ProjectId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Count.
        /// </summary>
        public static string ProjectsCount {
            get {
                return ResourceManager.GetString("ProjectsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Count.
        /// </summary>
        public static string RolesCount {
            get {
                return ResourceManager.GetString("RolesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Count.
        /// </summary>
        public static string RolesId {
            get {
                return ResourceManager.GetString("RolesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks Count.
        /// </summary>
        public static string TasksCount {
            get {
                return ResourceManager.GetString("TasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Do Tasks Count.
        /// </summary>
        public static string ToDoTasksCount {
            get {
                return ResourceManager.GetString("ToDoTasksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string User_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("User_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password and Confirm not match.
        /// </summary>
        public static string User_ConfirmPassword_Not_Match {
            get {
                return ResourceManager.GetString("User_ConfirmPassword_Not_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string User_NewPassword {
            get {
                return ResourceManager.GetString("User_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string User_OldPassword {
            get {
                return ResourceManager.GetString("User_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
