//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskoMask.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationMetadata {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationMetadata() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskoMask.Application.Resources.ApplicationMetadata", typeof(ApplicationMetadata).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description must have between {0} and {1} characters.
        /// </summary>
        public static string Description_Length_Error {
            get {
                return ResourceManager.GetString("Description_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Required.
        /// </summary>
        public static string Description_Required {
            get {
                return ResourceManager.GetString("Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name must have between {0} and {1} characters.
        /// </summary>
        public static string Name_Length_Error {
            get {
                return ResourceManager.GetString("Name_Length_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationId Required.
        /// </summary>
        public static string Organization_Required {
            get {
                return ResourceManager.GetString("Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganizationId Required.
        /// </summary>
        public static string OrganizationId_Required {
            get {
                return ResourceManager.GetString("OrganizationId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectId Required.
        /// </summary>
        public static string ProjectId_Required {
            get {
                return ResourceManager.GetString("ProjectId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User DisplayName Required.
        /// </summary>
        public static string User_DisplayName_Required {
            get {
                return ResourceManager.GetString("User_DisplayName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email Required.
        /// </summary>
        public static string User_Email_Required {
            get {
                return ResourceManager.GetString("User_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId Required.
        /// </summary>
        public static string UserId_Required {
            get {
                return ResourceManager.GetString("UserId_Required", resourceCulture);
            }
        }
    }
}
