//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskoMask.BuildingBlocks.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskoMask.BuildingBlocks.Domain.Resources.DomainMessages", typeof(DomainMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already exist.
        /// </summary>
        public static string Email_Already_Exist {
            get {
                return ResourceManager.GetString("Email_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be same of name.
        /// </summary>
        public static string Equal_Name_And_Description_Error {
            get {
                return ResourceManager.GetString("Equal_Name_And_Description_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong.
        /// </summary>
        public static string Incorrect_Old_Password {
            get {
                return ResourceManager.GetString("Incorrect_Old_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or username.
        /// </summary>
        public static string Incorrect_Password {
            get {
                return ResourceManager.GetString("Incorrect_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string Invalid_Email_Address {
            get {
                return ResourceManager.GetString("Invalid_Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber is invalid.
        /// </summary>
        public static string Invalid_PhoneNumber {
            get {
                return ResourceManager.GetString("Invalid_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project cannot have more than {0} boards.
        /// </summary>
        public static string Max_Board_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Board_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A board cannot have more than {0} cards.
        /// </summary>
        public static string Max_Card_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Card_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A board cannot have more than {0} members.
        /// </summary>
        public static string Max_Member_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Member_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An owner cannot have more than {0} organizations.
        /// </summary>
        public static string Max_Organizations_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Organizations_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization cannot have more than {0} projects.
        /// </summary>
        public static string Max_Projects_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Projects_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A board cannot have more than {0} tasks.
        /// </summary>
        public static string Max_Task_Count_Limitiation {
            get {
                return ResourceManager.GetString("Max_Task_Count_Limitiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name already exist.
        /// </summary>
        public static string Name_Already_Exist {
            get {
                return ResourceManager.GetString("Name_Already_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and email can not be the same.
        /// </summary>
        public static string UserName_And_Email_Cannot_Be_The_Same {
            get {
                return ResourceManager.GetString("UserName_And_Email_Cannot_Be_The_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and email must be the same.
        /// </summary>
        public static string UserName_And_Email_Must_Be_The_Same {
            get {
                return ResourceManager.GetString("UserName_And_Email_Must_Be_The_Same", resourceCulture);
            }
        }
    }
}
